name: saints
description: Lives of saints
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  auto_size_text: ^3.0.0
  flutter_svg: ^0.22.0
  sqflite: ^2.0.2
  easy_localization: ^3.0.0
  supercharged: ^2.1.1
  rate_my_app: ^1.1.0+1
  html2md: ^1.2.6
  fluttertoast: ^8.0.9
  gallery_saver: ^2.3.2
  share_plus: ^4.0.4
  launch_review: ^3.0.1
  visibility_detector: ^0.2.2

  flutter_toolkit:
    path: /Users/alexey/workspace/flutter_toolkit

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/db/
    - assets/icons/
    - assets/images/
    - assets/translations/
